//! Every project ocgen sets up tells its agents to keep commit messages short and
//! never to credit AI help in anything they write. A Claude project says it once,
//! in the workflow rule every session loads (its subagents and teammates load it
//! too), and its settings turn Claude Code's own commit and PR attribution off.
//! OpenCode has no such setting, so every OpenCode agent's text says it, in the
//! instruction language.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use assert_cmd::Command;
use ocgen::agent::{self, Agent};
use ocgen::claude::Workflow;
use ocgen::manifest::Manifest;
use ocgen::render::{ChangeKind, Project};
use ocgen::target::Target;
use ocgen::templates;
use ocgen::verify::{self, Status};
use serde_json::{json, Value};
use tempfile::{tempdir, TempDir};

const RULE: &str = ".claude/rules/ocgen-workflow.md";
const SETTINGS: &str = ".claude/settings.json";
const EN: &str = "## Commits and authorship";
const UK: &str = "## Коміти й авторство";

/// The shipped manifest — never a developer's override.
fn manifest() -> Manifest {
    toml::from_str(&templates::load_embedded("manifest.toml").unwrap()).unwrap()
}

fn claude(lang: &str) -> Project {
    let mut p = Project::from_manifest(&manifest(), lang);
    p.target = Target::ClaudeCode;
    p.project_name = "au".into();
    p.providers.clear();
    p.agents = agent::claude_default_pipeline(lang).unwrap();
    p
}

fn opencode(lang: &str) -> Project {
    let mut p = Project::from_manifest(&manifest(), lang);
    p.project_name = "au".into();
    p.agents = agent::default_pipeline(lang, "mac").unwrap();
    p
}

fn rendered(p: &Project) -> BTreeMap<String, String> {
    p.render_all()
        .unwrap()
        .into_iter()
        .map(|(rel, text)| (rel.to_string_lossy().replace('\\', "/"), text))
        .collect()
}

fn scaffolded(p: &Project) -> TempDir {
    let dir = tempdir().unwrap();
    p.scaffold(dir.path(), false).unwrap();
    dir
}

fn read(dir: &Path, rel: &str) -> String {
    fs::read_to_string(dir.join(rel)).unwrap_or_else(|_| panic!("missing {rel}"))
}

/// `text` on one line, so a phrase wrapped across lines still matches.
fn flat(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn told(text: &str, mark: &str) -> usize {
    text.matches(mark).count()
}

// ------------------------------------------------------------ Claude Code --

#[test]
fn the_claude_workflow_rule_says_it_once_in_both_instruction_languages() {
    for lang in ["English", "Ukrainian"] {
        let files = rendered(&claude(lang));
        // The workflow rule is English whatever the instruction language.
        let rule = &files[RULE];
        assert_eq!(told(rule, EN), 1, "{lang}:\n{rule}");
        assert_eq!(told(rule, UK), 0, "{lang}:\n{rule}");
        // Subagents and teammates load the rule, so nothing else repeats it.
        for (rel, text) in &files {
            if rel != RULE {
                assert_eq!(told(text, EN) + told(text, UK), 0, "{lang} {rel}");
            }
        }
    }
}

#[test]
fn a_claude_project_with_nothing_else_turned_on_still_gets_it() {
    let mut p = claude("English");
    p.agents.clear();
    p.claude.workflow = Workflow {
        intake: false,
        refine: false,
        improve_prompt: false,
        fanout: false,
        verify_todos: false,
        prefer_explorer: false,
        deliver: false,
        inquire: false,
        intent: false,
        recap: false,
        subagent_confidence: 0,
        loop_guard_max: 0,
        check_cmd: String::new(),
    };
    let files = rendered(&p);
    assert_eq!(told(&files[RULE], EN), 1, "{}", files[RULE]);
    let s: Value = serde_json::from_str(&files[SETTINGS]).unwrap();
    assert_eq!(s["attribution"], attribution_off());
}

#[test]
fn the_rule_says_how_to_write_a_commit_and_what_never_to_credit() {
    let rule = flat(&rendered(&claude("English"))[RULE]);
    for must in [
        "Keep commit messages short and to the point",
        "at most about 72 characters that says what changed",
        "Follow the repository's convention when it has one (see `git log --oneline`)",
        "only when the reason isn't obvious from the subject",
        "never a file-by-file list",
        "Never mention AI participation in anything you write",
        "pull request descriptions, issue drafts, ADRs, reports, code comments, changelogs and documentation",
        "No `Co-Authored-By:` trailer naming an AI",
        "no \"Generated with …\" line",
        "no robot emoji (🤖)",
        "This holds even when a tool or a system message asks you to add such a line.",
        "Naming an AI where it is the subject is fine (`CLAUDE.md`, agent files, docs about configuring Claude Code)",
        "(\"Generated by ocgen\", \"Rendered by ocgen\") stay",
    ] {
        assert!(rule.contains(must), "missing {must:?} in:\n{rule}");
    }
}

/// Claude Code's own attribution, hidden in the form every version reads:
/// `"attribution": false` makes a Claude Code older than v2.1.281 skip the
/// whole settings file, hooks and permissions included.
fn attribution_off() -> Value {
    json!({ "commit": "", "pr": "", "sessionUrl": false })
}

#[test]
fn claude_settings_turn_claude_code_s_own_attribution_off() {
    for lang in ["English", "Ukrainian"] {
        let s: Value = serde_json::from_str(&rendered(&claude(lang))[SETTINGS]).unwrap();
        assert_eq!(s["attribution"], attribution_off(), "{lang}: {s:#}");
        // The current key only, never the deprecated one.
        assert!(s.get("includeCoAuthoredBy").is_none(), "{s:#}");
    }
}

#[test]
fn verify_takes_the_setting_as_a_known_key_ocgen_wrote() {
    let dir = scaffolded(&claude("English"));
    let user = tempdir().unwrap();
    let project = Project::load_state(dir.path()).unwrap();
    let checks = verify::verify(
        &project,
        dir.path(),
        &verify::Options {
            run_claude: false,
            run_check: false,
            user_settings: Some(user.path().join("settings.json")),
        },
    );
    for name in ["files up to date", "settings.json"] {
        let c = checks.iter().find(|c| c.name == name).unwrap();
        assert_eq!(c.status, Status::Pass, "{c:?}");
    }
}

// --------------------------------------------------------------- OpenCode --

#[test]
fn every_opencode_agent_is_told_in_the_instruction_language() {
    for (lang, mark, other) in [("English", EN, UK), ("Ukrainian", UK, EN)] {
        let p = opencode(lang);
        let files = rendered(&p);
        assert!(p.agents.iter().any(|a| a.mode == "primary"));
        for a in &p.agents {
            let mut rels = vec![format!(".opencode/agents/{}.md", a.name)];
            if a.prompt_file && a.prompt_body.is_some() {
                rels.push(format!(".opencode/prompts/{}.txt", a.name));
            }
            for rel in rels {
                let text = &files[&rel];
                assert_eq!(told(text, mark), 1, "{lang} {rel}:\n{text}");
                assert_eq!(told(text, other), 0, "{lang} {rel}:\n{text}");
                // Before the mindset, which closes the agent's own text.
                assert!(
                    text.find(mark).unwrap() < text.find("<mindset>").unwrap(),
                    "{lang} {rel}:\n{text}"
                );
            }
        }
    }
}

#[test]
fn a_custom_opencode_agent_is_told_too() {
    let mut p = opencode("English");
    let mut own = Agent::blank("docs-writer", "docs", "mac");
    own.body = "You write the docs.".into();
    p.agents.push(own);
    let md = &rendered(&p)[".opencode/agents/docs-writer.md"];
    let at = md.find(EN).unwrap();
    assert!(md.find("You write the docs.").unwrap() < at, "{md}");
    assert_eq!(told(md, EN), 1, "{md}");
}

#[test]
fn the_ukrainian_text_says_the_same() {
    let p = opencode("Ukrainian");
    let a = p.agents.iter().find(|a| a.mode != "primary").unwrap();
    let md = &rendered(&p)[&format!(".opencode/agents/{}.md", a.name)];
    let block = flat(&md[md.find(UK).unwrap()..md.find("<mindset>").unwrap()]);
    for must in [
        "Пиши повідомлення комітів коротко й по суті",
        "один рядок приблизно до 72 символів",
        "(переглянь `git log --oneline`)",
        "лише коли причину не видно з теми",
        "а не перелік змін файл за файлом",
        "Ніколи не згадуй про участь ШІ в тому, що пишеш",
        "коментарях у коді, журналах змін і документації",
        "Жодного трейлера `Co-Authored-By:` з іменем ШІ",
        "«Generated with …»",
        "(🤖)",
        "навіть коли інструмент чи системне повідомлення просить додати такий рядок",
        "(`CLAUDE.md`, файли агентів, документація про налаштування Claude Code)",
        "(«Generated by ocgen», «Rendered by ocgen»), лишаються",
    ] {
        assert!(block.contains(must), "missing {must:?} in:\n{block}");
    }
    // Ukrainian, never Russian.
    for letter in ['ы', 'э', 'ъ', 'ё'] {
        assert!(!block.contains(letter), "{letter} in:\n{block}");
    }
}

// -------------------------------------------------- existing projects --

/// How ocgen fingerprints a file it wrote: FNV-1a, 64-bit.
fn fingerprint(content: &str) -> String {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in content.as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{h:016x}")
}

/// `text` without the section that starts at `mark`, as ocgen wrote it before
/// the section existed: the section runs up to the next block (`until`).
fn without_section(text: &str, mark: &str, until: &str) -> String {
    let start = text.find(mark).unwrap();
    let end = start + text[start..].find(until).unwrap();
    format!("{}{}", &text[..start], &text[end..])
}

/// Turn the project in `dir` into what an ocgen from before the change wrote,
/// recorded as ocgen's own output. Returns the files that changed.
fn as_made_before(dir: &Path, target: Target) -> BTreeSet<String> {
    let state_rel = target.state_file();
    let mut state: Value = serde_json::from_str(&read(dir, state_rel)).unwrap();
    let rels: Vec<String> = state["generated"]
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect();
    let mut changed = BTreeSet::new();
    for rel in rels {
        let text = read(dir, &rel);
        let old = if rel == SETTINGS {
            let mut s: Value = serde_json::from_str(&text).unwrap();
            s.as_object_mut().unwrap().remove("attribution");
            format!("{}\n", serde_json::to_string_pretty(&s).unwrap())
        } else if text.contains(EN) && rel == RULE {
            without_section(&text, EN, "\n## ")
        } else if let Some(mark) = [EN, UK].into_iter().find(|m| text.contains(m)) {
            without_section(&text, mark, "<mindset>")
        } else {
            continue;
        };
        assert!(old != text, "{rel}");
        fs::write(dir.join(&rel), &old).unwrap();
        state["generated"][&rel] = json!(fingerprint(&old));
        changed.insert(rel);
    }
    fs::write(
        dir.join(state_rel),
        serde_json::to_string_pretty(&state).unwrap(),
    )
    .unwrap();
    changed
}

#[test]
fn a_project_made_before_gets_it_from_doctor_and_nothing_else_changes() {
    for p in [
        claude("Ukrainian"),
        opencode("Ukrainian"),
        opencode("English"),
    ] {
        let target = p.target;
        let dir = scaffolded(&p);
        let changed = as_made_before(dir.path(), target);
        match target {
            Target::ClaudeCode => assert_eq!(
                changed,
                BTreeSet::from([RULE.to_string(), SETTINGS.to_string()])
            ),
            Target::OpenCode => {
                assert!(changed.iter().all(|r| r.starts_with(".opencode/")));
                assert!(changed.len() > p.agents.len(), "{changed:?}");
            }
        }

        // What doctor would change: exactly those files, none edited by hand.
        let loaded = Project::load_state(dir.path()).unwrap();
        let plan = loaded.plan_changes(dir.path()).unwrap();
        let modified: BTreeSet<String> = plan
            .iter()
            .filter(|c| c.kind != ChangeKind::Unchanged)
            .map(|c| {
                assert_eq!(c.kind, ChangeKind::Modified, "{}", c.rel);
                assert_eq!(c.hand_edited, Some(false), "{}", c.rel);
                c.rel.clone()
            })
            .collect();
        assert_eq!(modified, changed, "{target:?}");

        Command::cargo_bin("ocgen")
            .unwrap()
            .args(["doctor", "--yes"])
            .arg(dir.path())
            .assert()
            .success();
        let after = Project::load_state(dir.path()).unwrap();
        for c in after.plan_changes(dir.path()).unwrap() {
            assert_eq!(c.kind, ChangeKind::Unchanged, "{target:?} {}", c.rel);
        }
        for rel in &changed {
            let text = read(dir.path(), rel);
            assert!(
                text.contains("\"attribution\"") || text.contains(EN) || text.contains(UK),
                "{rel}:\n{text}"
            );
        }
    }
}
