#!/bin/sh
# Claude Code status line (generated by ocgen):
#   model · folder (branch) · context left · session cost · worktree · unresolved
#   loop-guard escalations
# Reads the status JSON on stdin. Uses jq when available, plain sh otherwise.
input=$(cat | tr '\n' ' ')

if [ -z "${OCGEN_STATUSLINE_NO_JQ:-}" ] && command -v jq >/dev/null 2>&1; then
    get() { printf '%s' "$input" | jq -r "$1 // empty" 2>/dev/null; }
    model=$(get '.model.display_name')
    dir=$(get '.workspace.current_dir')
    proj=$(get '.workspace.project_dir')
    left=$(get '.context_window.remaining_percentage')
    cost=$(get '.cost.total_cost_usd')
    wt=$(get '.worktree.name')
else
    # str/num <json> <key>: the first "key": value in that JSON fragment.
    str() { printf '%s' "$1" | grep -oE "\"$2\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -n 1 |
        sed -E 's/^.*:[[:space:]]*"([^"]*)"$/\1/'; }
    num() { printf '%s' "$1" | grep -oE "\"$2\"[[:space:]]*:[[:space:]]*[0-9.]+" | head -n 1 |
        sed -E 's/^.*:[[:space:]]*//'; }
    # after <key>: everything following "key": { — scopes a lookup to that object.
    after() { printf '%s' "$input" | sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*{//p"; }
    model=$(str "$(after model)" display_name)
    dir=$(str "$input" current_dir)
    proj=$(str "$input" project_dir)
    left=$(num "$(after context_window)" remaining_percentage)
    cost=$(num "$(after cost)" total_cost_usd)
    wt=$(str "$(after worktree)" name)
fi
if [ -z "$proj" ]; then
    proj=${CLAUDE_PROJECT_DIR:-$(git -C "${dir:-.}" --no-optional-locks rev-parse --show-toplevel 2>/dev/null)}
    proj=${proj:-$dir}
fi

DIM='\033[2m'
YEL='\033[33m'
RED='\033[31m'
RST='\033[0m'
out=""
add() { out="${out:+$out  }$1"; }

[ -n "$model" ] && add "${DIM}${model}${RST}"
if [ -n "$dir" ]; then
    place=$(basename "$dir")
    # --no-optional-locks: never block on a concurrent git process.
    branch=$(git -C "$dir" --no-optional-locks branch --show-current 2>/dev/null)
    [ -n "$branch" ] && place="$place ($branch)"
    add "${DIM}${place}${RST}"
fi
if [ -n "$left" ]; then
    l=${left%%.*}
    c=$DIM
    [ "$l" -lt 30 ] 2>/dev/null && c=$YEL
    [ "$l" -lt 15 ] 2>/dev/null && c=$RED
    add "${c}${l}% left${RST}"
fi
case "$cost" in
'' | 0 | 0.0 | 0.00) ;;
*) add "${DIM}\$$(printf '%.2f' "$cost" 2>/dev/null)${RST}" ;;
esac
[ -n "$wt" ] && add "${DIM}wt:${wt}${RST}"
# Work the loop guard released as UNRESOLVED; delete the file once reviewed.
esc="$proj/.claude/loop-guard/escalations.md"
if [ -n "$proj" ] && [ -f "$esc" ]; then
    n=$(grep -c '^- ' "$esc" 2>/dev/null)
    [ "${n:-0}" -gt 0 ] 2>/dev/null && add "${RED}⚠ ${n} unresolved${RST}"
fi
printf '%b\n' "$out"
